version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  nestjs_rate_limiter_0:
    container_name: nestjs_rate_limiter_0
    build:
      context: .
      args:
        PORT: 3000
    expose:
      - '3000'
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - redis

  nestjs_rate_limiter_1:
    container_name: nestjs_rate_limiter_1
    build:
      context: .
      args:
        PORT: 3001
    expose:
      - '3001'
    ports:
      - 3001:3001
    env_file: .env
    depends_on:
      - redis
