export enum EnvEnum {
  PORT = 'PORT',
  AUTH_TOKEN = 'AUTH_TOKEN',
  REDIS_URL = 'REDIS_URL',
  RATE_LIMIT_BY_TOKEN = 'RATE_LIMIT_BY_TOKEN',
  RATE_LIMIT_BY_IP = 'RATE_LIMIT_BY_IP',
  WINDOW_SIZE_IN_SECONDS = 'WINDOW_SIZE_IN_SECONDS',
}
